name: Miles Away
description: Two millennial men trying to find their way.

url: http://wsankey.github.com/miles-away
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
pygments: true
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
